# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements
      # - id: double-quote-string-fixer
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
